"""Thin durable semantic-governor store contracts over DurableCoordinationStore.

SCG-010 freezes the closed protocol surface.  Later tasks (SCG-019–SCG-022)
implement artifacts, histories, policy/promotion CAS, and recovery without
opening a second storage engine or receipt hierarchy.
"""

from __future__ import annotations

from ipfs_kit_py.semantic_governor_store.contracts import (
    CONTRACT_VERSION,
    GOVERNOR_NAMESPACE_PREFIX,
    MAX_NAMESPACE_CHARS,
    MAX_OPERATION_ID_CHARS,
    MAX_RECOVERY_ERRORS,
    SEMANTIC_GOVERNOR_STORE_INTERFACE,
    SEMANTIC_GOVERNOR_STORE_SCHEMA,
    AuditHistoryStore,
    AuditRecoveryReport,
    CompressionPolicyRepository,
    GovernorArtifactKind,
    GovernorArtifactWriteResult,
    GovernorHistoryRole,
    GovernorNamespaceRole,
    GovernorProviderStatus,
    GovernorStoreStatus,
    HistoryAppendResult,
    HistoryHeadSnapshot,
    PolicyCASResult,
    PolicyVersionSnapshot,
    PromotionCASResult,
    PromotionStateRepository,
    PromotionStateSnapshot,
    ReceiptIssuanceResult,
    SemanticGovernorStore,
    SemanticGovernorStoreContractError,
    governor_artifact_kinds,
    governor_namespace,
    governor_namespace_roles,
    governor_store_statuses,
    history_namespace,
    parse_governor_namespace,
    validate_generation_expectation,
    validate_governor_namespace,
    validate_governor_workspace,
    validate_operation_id,
    validate_reason_code,
    validate_semantic_dag_json_cid,
    validate_verified_cid,
)

__all__ = [
    "CONTRACT_VERSION",
    "SEMANTIC_GOVERNOR_STORE_INTERFACE",
    "SEMANTIC_GOVERNOR_STORE_SCHEMA",
    "GOVERNOR_NAMESPACE_PREFIX",
    "MAX_NAMESPACE_CHARS",
    "MAX_OPERATION_ID_CHARS",
    "MAX_RECOVERY_ERRORS",
    "SemanticGovernorStoreContractError",
    "GovernorArtifactKind",
    "GovernorNamespaceRole",
    "GovernorStoreStatus",
    "GovernorProviderStatus",
    "GovernorHistoryRole",
    "GovernorArtifactWriteResult",
    "PolicyVersionSnapshot",
    "PromotionStateSnapshot",
    "HistoryHeadSnapshot",
    "PolicyCASResult",
    "PromotionCASResult",
    "HistoryAppendResult",
    "ReceiptIssuanceResult",
    "AuditRecoveryReport",
    "AuditHistoryStore",
    "CompressionPolicyRepository",
    "PromotionStateRepository",
    "SemanticGovernorStore",
    "validate_governor_workspace",
    "validate_governor_namespace",
    "validate_operation_id",
    "validate_reason_code",
    "validate_verified_cid",
    "validate_semantic_dag_json_cid",
    "validate_generation_expectation",
    "governor_namespace",
    "parse_governor_namespace",
    "history_namespace",
    "governor_artifact_kinds",
    "governor_namespace_roles",
    "governor_store_statuses",
]
