apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-master-data
  namespace: ipfs-kit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-worker-data
  namespace: ipfs-kit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
# StorageClass for faster SSD-based storage (for master node)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ipfs-ssd
  namespace: ipfs-kit
provisioner: kubernetes.io/gce-pd # Adjust for your cloud provider
parameters:
  type: pd-ssd
  fstype: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
---
# StorageClass for high-capacity HDD-based storage (for worker nodes)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ipfs-hdd
  namespace: ipfs-kit
provisioner: kubernetes.io/gce-pd # Adjust for your cloud provider
parameters:
  type: pd-standard
  fstype: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true