"""Versioned Python boundary for the managed IPFS Kit Iroh runtime."""

from . import errors as _errors

from .client import (
    CLIAdapter,
    DiagnosticCLIAdapter,
    IrohRuntimeClient,
    RPCAdapter,
    RuntimeClient,
    SidecarAdapter,
    SidecarRPCAdapter,
    redact,
    redact_secrets,
)
from .blob_store import (
    BlobExportResult,
    BlobInfo,
    BlobIngestResult,
    BlobStore,
    ExportResult,
    IngestResult,
    IrohBlobStore,
    TransferProgress,
    validate_blob_hash,
)
from .config import (
    CONFIG_SCHEMA_VERSION,
    DEFAULT_INSTANCE,
    DEFAULT_PROTOCOL_VERSION,
    DEFAULT_RELEASE_BUNDLE,
    DIRECTORY_MODE,
    FILE_MODE,
    IrohServiceConfig,
    IrohStateLayout,
    OwnershipPolicy,
    ResourceLimits,
    ServiceConfig,
    StateLayout,
    atomic_write_config,
    default_config,
    default_state_root,
    ensure_state_layout,
    load_config,
    load_service_config,
    loads_config,
    migrate_config,
    migrate_config_file,
    migrate_service_config,
    parse_config,
    save_config,
    validate_instance_isolation,
    validate_instance_name,
)
from .errors import *  # noqa: F403 - errors are the package's public vocabulary
from .protocol import (
    PROTOCOL_VERSION,
    REQUIRED_METHODS,
    Capabilities,
    CapabilitySet,
    IrohRequest,
    IrohResult,
    RPCError,
    RPCRequest,
    RPCResponse,
    RuntimeCapabilities,
    RuntimeVersion,
    VersionInfo,
)
from .observability import (
    HEALTH_KIND,
    HEALTH_SCHEMA_VERSION,
    HealthReceipt,
    IrohHealthMonitor,
    IrohHealthReceipt,
    IrohObservability,
    Observability,
    collect_health,
    collect_metrics,
    metrics_from_receipt,
    normalize_health,
    prometheus_from_receipt,
    render_prometheus,
)
from .manifest import (
    DIRECTORY_MODES,
    FILE_MODES,
    MANIFEST_SCHEMA_VERSION,
    DirectoryManifest,
    IrohManifestStore,
    Manifest,
    ManifestEntry,
    ManifestHead,
    ManifestPermissions,
    ManifestSnapshot,
    ManifestStore,
    ParentRevision,
    RecoveryReceipt,
    canonical_manifest_bytes,
    manifest_hash,
    migrate_manifest,
    migrate_manifest_json,
    validate_manifest,
    validate_manifest_path,
)
from .gc import (
    DEFAULT_RETENTION_SECONDS,
    GC_RECEIPT_KIND,
    GC_RECEIPT_SCHEMA_VERSION,
    GC_SCHEMA_VERSION,
    GarbageCollector,
    GCCandidate,
    GCFailure,
    GCMark,
    GCPolicy,
    GCReceipt,
    IrohGarbageCollector,
    Lease,
    LeaseHandle,
    MAX_LEASE_SECONDS,
    QuotaStatus,
    ReferenceIndex,
    ReferenceTracker,
    RepairReceipt,
    verify_gc_receipt,
)


def __getattr__(name: str):
    """Load lifecycle symbols lazily, preserving side-effect-free imports.

    Lazy loading also permits ``python -m ipfs_kit_py.iroh.service`` without
    pre-importing the module through this package initializer.
    """

    if name in {"IrohService", "LifecycleMode"}:
        from .service import IrohService, LifecycleMode

        return {"IrohService": IrohService, "LifecycleMode": LifecycleMode}[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "PROTOCOL_VERSION",
    "REQUIRED_METHODS",
    "RPCRequest",
    "RPCResponse",
    "RPCError",
    "RuntimeVersion",
    "RuntimeCapabilities",
    "IrohRequest",
    "IrohResult",
    "VersionInfo",
    "Capabilities",
    "CapabilitySet",
    "RPCAdapter",
    "SidecarRPCAdapter",
    "DiagnosticCLIAdapter",
    "IrohRuntimeClient",
    "RuntimeClient",
    "SidecarAdapter",
    "CLIAdapter",
    "redact",
    "redact_secrets",
    "BlobInfo",
    "IngestResult",
    "ExportResult",
    "TransferProgress",
    "IrohBlobStore",
    "BlobStore",
    "BlobIngestResult",
    "BlobExportResult",
    "validate_blob_hash",
    "CONFIG_SCHEMA_VERSION",
    "DEFAULT_RELEASE_BUNDLE",
    "DEFAULT_PROTOCOL_VERSION",
    "DEFAULT_INSTANCE",
    "DIRECTORY_MODE",
    "FILE_MODE",
    "IrohStateLayout",
    "IrohServiceConfig",
    "ResourceLimits",
    "OwnershipPolicy",
    "ServiceConfig",
    "StateLayout",
    "default_state_root",
    "validate_instance_name",
    "default_config",
    "parse_config",
    "loads_config",
    "load_config",
    "load_service_config",
    "atomic_write_config",
    "save_config",
    "ensure_state_layout",
    "validate_instance_isolation",
    "migrate_config",
    "migrate_service_config",
    "migrate_config_file",
    "IrohService",
    "LifecycleMode",
    "HEALTH_KIND",
    "HEALTH_SCHEMA_VERSION",
    "HealthReceipt",
    "IrohHealthReceipt",
    "IrohHealthMonitor",
    "IrohObservability",
    "Observability",
    "collect_health",
    "collect_metrics",
    "metrics_from_receipt",
    "normalize_health",
    "prometheus_from_receipt",
    "render_prometheus",
    "MANIFEST_SCHEMA_VERSION",
    "FILE_MODES",
    "DIRECTORY_MODES",
    "ParentRevision",
    "ManifestPermissions",
    "ManifestEntry",
    "DirectoryManifest",
    "Manifest",
    "ManifestHead",
    "ManifestSnapshot",
    "RecoveryReceipt",
    "IrohManifestStore",
    "ManifestStore",
    "validate_manifest",
    "canonical_manifest_bytes",
    "manifest_hash",
    "migrate_manifest",
    "migrate_manifest_json",
    "validate_manifest_path",
    "GC_SCHEMA_VERSION",
    "GC_RECEIPT_SCHEMA_VERSION",
    "GC_RECEIPT_KIND",
    "DEFAULT_RETENTION_SECONDS",
    "MAX_LEASE_SECONDS",
    "GCPolicy",
    "Lease",
    "LeaseHandle",
    "QuotaStatus",
    "RepairReceipt",
    "GCCandidate",
    "GCMark",
    "GCFailure",
    "GCReceipt",
    "ReferenceTracker",
    "ReferenceIndex",
    "IrohGarbageCollector",
    "GarbageCollector",
    "verify_gc_receipt",
] + list(_errors.__all__)
