name: Pre-Release Deprecation Check

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  deprecation-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn psutil pyyaml
      - name: Run deprecation verification
        run: |
          python verify_deprecations.py --version "${GITHUB_REF_NAME#v}"
