name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

permissions:
  contents: read
  security-events: write

jobs:
  dependency-check:
    name: Dependency Check on ${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'arm64' && fromJSON('["self-hosted", "arm64", "dgx"]') || 'ubuntu-20.04' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python (AMD64)
      if: matrix.arch == 'amd64'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Set up Python (ARM64)
      if: matrix.arch == 'arm64'
      run: |
        if command -v python3.11 >/dev/null 2>&1; then
          python3.11 -m venv venv
        else
          python3 -m venv venv
        fi
        source venv/bin/activate
        echo "venv/bin" >> $GITHUB_PATH
    
    - name: Install safety
      run: pip install safety
    
    - name: Check dependencies
      run: |
        pip install -e ".[dev]"
        safety check

  bandit-scan:
    name: Bandit Scan on ${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'arm64' && fromJSON('["self-hosted", "arm64", "dgx"]') || 'ubuntu-20.04' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python (AMD64)
      if: matrix.arch == 'amd64'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Set up Python (ARM64)
      if: matrix.arch == 'arm64'
      run: |
        if command -v python3.11 >/dev/null 2>&1; then
          python3.11 -m venv venv
        else
          python3 -m venv venv
        fi
        source venv/bin/activate
        echo "venv/bin" >> $GITHUB_PATH
    
    - name: Install bandit
      run: pip install bandit
    
    - name: Run bandit scan
      run: bandit -r ipfs_kit_py -ll
      
  docker-scan:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        load: true
        tags: ipfs-kit-py:test-scan
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ipfs-kit-py:test-scan
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'